---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  {% if cookiecutter.ingress != "none" -%}
  - ../../components/db
  {%- endif %}
  {% if cookiecutter.database != "none" -%}
  - db-secret.yaml
  {%- endif %}
namespace: "{{ cookiecutter.namespace }}"
namePrefix: "{{ cookiecutter.service_name }}-"
images:
  - name: "{{ cookiecutter.app_image }}"
    newTag: "{{ cookiecutter.tag }}"
  {% if cookiecutter.database != "none" -%}
  - name: "docker.io/bitnami/postgresql"
    newTag: "15.3.0-debian-11-r9"
  {%- endif %}
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  {% if cookiecutter.database != "none" -%}
  # we're going to trigger the rollout by additionally having a generated
  # config map that changes when the sealed secret is updated.
  # See: https://github.com/kubernetes-sigs/kustomize/issues/702
  - name: db-sentinel
    files:
      - db-secret.yaml
  # for configuring the db statefulset
  - name: db-config
    envs:
      - db-config.env
  # for configuring app(s) to talk to the db
  - name: db-connect
    envs:
      - db-connect.env
  {%- endif %}
