---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "{{ cookiecutter.namespace }}"
namePrefix: "{{ cookiecutter.service_name }}-"
images:
  - name: "{{ cookiecutter.app_image }}"
    newTag: "{{ cookiecutter.tag }}"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
