apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: "db-secret"
  namespace: {{ cookiecutter.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: "REPLACE_POSTGRES_PASSWORD"
  POSTGRES_POSTGRES_PASSWORD: "REPLACE_POSTGRES_POSTGRES_PASSWORD"
