---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "{{ cookiecutter.app_image }}:{{ cookiecutter.tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
            {% if cookiecutter.database != "none" -%}
            - configMapRef:
                name: "db-sentinel"
            - configMapRef:
                name: "db-connect"
            - secretRef:
                # we can't let kustomize handle this because this secret is
                # unknown to it because it's the result of unsealing the secret
                name: "{{ cookiecutter.service_name}}-db-secret"
            {%- endif %}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
